export type IconName =
	| "Godot"
	| "GameController"
	| "Desktop"
	| "OpenAI"
	| "Terminal"
	| "Phone"
	| "Puzzle"
	| "Arrow"
	| "Angular"
	| "Ionic"
	| "Capacitor"
	| "Download"
	| "Nextjs"
	| "TailwindCSS"
	| "Vercel"
	| "Square"
	| "HeroLightning"
	| "Storybook"
	| "TypeScript"
	| "Threejs"
	| "NodeJS"
	| "React"
	| "LinkedIn"
	| "GitHub";

export type AriaType = "decorative" | "stand-alone" | "hidden"; // https://css-tricks.com/accessible-svg-icons/
